images = [
	"./res/images/rabbitv3.png",
	"./res/images/rabbitv3_ash.png",
	"./res/images/rabbitv3_batman.png",
	"./res/images/rabbitv3_bb8.png",
	"./res/images/rabbitv3_frankenstein.png",
	"./res/images/rabbitv3_neo.png",
	"./res/images/rabbitv3_sonic.png",
	"./res/images/rabbitv3_spidey.png",
	"./res/images/rabbitv3_stormtrooper.png",
	"./res/images/rabbitv3_superman.png",
	"./res/images/rabbitv3_tron.png",
	"./res/images/rabbitv3_wolverine.png",
]
